# Generated by Django 6.0.3 on 2026-03-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('involved', models.CharField(max_length=20)),
                ('occupancy', models.CharField(blank=True, default='', max_length=120)),
                ('damage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('injured', models.PositiveIntegerField(default=0)),
                ('casualty', models.PositiveIntegerField(default=0)),
                ('station', models.CharField(blank=True, default='', max_length=60)),
                ('engine', models.CharField(blank=True, default='', max_length=60)),
                ('alarm', models.CharField(default='1st Alarm', max_length=20)),
                ('inputter', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('color_class', models.CharField(default='u1', max_length=10)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
